import { MovieDetail } from '../types/movie';

export const MOCK_MOVIES: MovieDetail[] = [
  {
    Title: "Inception",
    Year: "2010",
    Rated: "PG-13",
    Released: "16 Jul 2010",
    Runtime: "148 min",
    Genre: "Action, Adventure, Sci-Fi",
    Director: "Christopher Nolan",
    Writer: "Christopher Nolan",
    Actors: "Leonardo DiCaprio, Joseph Gordon-Levitt, Elliot Page, Tom Hardy",
    Plot: "A thief who steals corporate secrets through the use of dream-sharing technology is given the inverse task of planting an idea into the mind of a C.E.O., but his tragic past may doom the project and his team to disaster.",
    Language: "English, Japanese, French",
    Country: "United States, United Kingdom",
    Awards: "Won 4 Oscars. 159 wins & 220 nominations total",
    Poster: "https://m.media-amazon.com/images/M/MV5BMjAxMzY3NjcxNF5BMl5BanBnXkFtZTcwNTI5OTM0Mw@@._V1_SX300.jpg",
    Ratings: [
      { Source: "Internet Movie Database", Value: "8.8/10" },
      { Source: "Rotten Tomatoes", Value: "87%" },
      { Source: "Metacritic", Value: "74/100" }
    ],
    Metascore: "74",
    imdbRating: "8.8",
    imdbVotes: "2,540,123",
    imdbID: "tt1375666",
    Type: "movie",
    BoxOffice: "$292,587,330",
    Production: "Warner Bros. Pictures, Legendary Pictures",
    Response: "True"
  },
  {
    Title: "Interstellar",
    Year: "2014",
    Rated: "PG-13",
    Released: "07 Nov 2014",
    Runtime: "169 min",
    Genre: "Adventure, Drama, Sci-Fi",
    Director: "Christopher Nolan",
    Writer: "Jonathan Nolan, Christopher Nolan",
    Actors: "Matthew McConaughey, Anne Hathaway, Jessica Chastain, Michael Caine",
    Plot: "When Earth becomes uninhabitable in the future, a farmer and ex-NASA pilot, Joseph Cooper, is tasked to pilot a spacecraft, along with a team of researchers, to find a new planet for humans.",
    Language: "English",
    Country: "United States, United Kingdom, Canada",
    Awards: "Won 1 Oscar. 44 wins & 148 nominations total",
    Poster: "https://m.media-amazon.com/images/M/MV5BYzdjMDAxZGItMjSub2FjOS00N2Q3LThhNDUtYTI1Yzc2ODVhMWVlXkEyXkFqcGc@._V1_SX300.jpg",
    Ratings: [
      { Source: "Internet Movie Database", Value: "8.7/10" },
      { Source: "Rotten Tomatoes", Value: "73%" },
      { Source: "Metacritic", Value: "74/100" }
    ],
    Metascore: "74",
    imdbRating: "8.7",
    imdbVotes: "2,042,390",
    imdbID: "tt0816692",
    Type: "movie",
    BoxOffice: "$188,020,017",
    Production: "Paramount Pictures, Warner Bros.",
    Response: "True"
  },
  {
    Title: "The Dark Knight",
    Year: "2008",
    Rated: "PG-13",
    Released: "18 Jul 2008",
    Runtime: "152 min",
    Genre: "Action, Crime, Drama",
    Director: "Christopher Nolan",
    Writer: "Jonathan Nolan, Christopher Nolan, David S. Goyer",
    Actors: "Christian Bale, Heath Ledger, Aaron Eckhart, Michael Caine",
    Plot: "When the menace known as the Joker wreaks havoc and chaos on the people of Gotham, Batman must accept one of the greatest psychological and physical tests of his ability to fight injustice.",
    Language: "English, Mandarin",
    Country: "United States, United Kingdom",
    Awards: "Won 2 Oscars. 163 wins & 163 nominations total",
    Poster: "https://m.media-amazon.com/images/M/MV5BMTMxNTMwODM0NF5BMl5BanBnXkFtZTcwODAyMTk2Mw@@._V1_SX300.jpg",
    Ratings: [
      { Source: "Internet Movie Database", Value: "9.0/10" },
      { Source: "Rotten Tomatoes", Value: "94%" },
      { Source: "Metacritic", Value: "84/100" }
    ],
    Metascore: "84",
    imdbRating: "9.0",
    imdbVotes: "2,890,145",
    imdbID: "tt0468569",
    Type: "movie",
    BoxOffice: "$534,987,076",
    Production: "Warner Bros., Legendary Entertainment",
    Response: "True"
  },
  {
    Title: "Oppenheimer",
    Year: "2023",
    Rated: "R",
    Released: "21 Jul 2023",
    Runtime: "180 min",
    Genre: "Biography, Drama, History",
    Director: "Christopher Nolan",
    Writer: "Christopher Nolan, Kai Bird, Martin Sherwin",
    Actors: "Cillian Murphy, Emily Blunt, Matt Damon, Robert Downey Jr.",
    Plot: "The story of American scientist J. Robert Oppenheimer and his role in the development of the atomic bomb during World War II.",
    Language: "English, German, Italian",
    Country: "United States, United Kingdom",
    Awards: "Won 7 Oscars. 385 wins & 389 nominations total",
    Poster: "https://m.media-amazon.com/images/M/MV5BN2JkMDc5MGQtZjg3YS00NmFiLWIyZmQtZTGCYmNmZjY5M2M5XkEyXkFqcGc@._V1_SX300.jpg",
    Ratings: [
      { Source: "Internet Movie Database", Value: "8.9/10" },
      { Source: "Rotten Tomatoes", Value: "93%" },
      { Source: "Metacritic", Value: "90/100" }
    ],
    Metascore: "90",
    imdbRating: "8.9",
    imdbVotes: "780,240",
    imdbID: "tt15398776",
    Type: "movie",
    BoxOffice: "$329,862,540",
    Production: "Universal Pictures, Syncopy",
    Response: "True"
  },
  {
    Title: "Dune: Part Two",
    Year: "2024",
    Rated: "PG-13",
    Released: "01 Mar 2024",
    Runtime: "166 min",
    Genre: "Action, Adventure, Drama, Sci-Fi",
    Director: "Denis Villeneuve",
    Writer: "Denis Villeneuve, Jon Spaihts, Frank Herbert",
    Actors: "Timothée Chalamet, Zendaya, Rebecca Ferguson, Javier Bardem",
    Plot: "Paul Atreides unites with Chani and the Fremen while seeking revenge against the conspirators who destroyed his family.",
    Language: "English",
    Country: "United States, Canada",
    Awards: "Nominated for 5 Saturn Awards",
    Poster: "https://m.media-amazon.com/images/M/MV5BNTc0YmQxMjEtODI5MC00NjFiLTlkMWUtOGQ5NjFmYWU2M2U1XkEyXkFqcGc@._V1_SX300.jpg",
    Ratings: [
      { Source: "Internet Movie Database", Value: "8.6/10" },
      { Source: "Rotten Tomatoes", Value: "92%" },
      { Source: "Metacritic", Value: "79/100" }
    ],
    Metascore: "79",
    imdbRating: "8.6",
    imdbVotes: "480,100",
    imdbID: "tt15239678",
    Type: "movie",
    BoxOffice: "$282,144,358",
    Production: "Warner Bros., Legendary Pictures",
    Response: "True"
  },
  {
    Title: "Stranger Things",
    Year: "2016–2025",
    Rated: "TV-14",
    Released: "15 Jul 2016",
    Runtime: "51 min",
    Genre: "Drama, Fantasy, Horror, Sci-Fi",
    Director: "Matt Duffer, Ross Duffer",
    Writer: "Matt Duffer, Ross Duffer",
    Actors: "Millie Bobby Brown, Finn Wolfhard, Winona Ryder, David Harbour",
    Plot: "When a young boy vanishes, a small town uncovers a mystery involving secret experiments, terrifying supernatural forces and one strange little girl.",
    Language: "English, Russian",
    Country: "United States",
    Awards: "Won 12 Primetime Emmys. 132 wins & 352 nominations total",
    Poster: "https://m.media-amazon.com/images/M/MV5BMDZkYmVhNjMtNWU4MC00MDQxLWE3YTItYjKwZGE0ZDVkZDNmXkEyXkFqcGc@._V1_SX300.jpg",
    Ratings: [
      { Source: "Internet Movie Database", Value: "8.7/10" },
      { Source: "Rotten Tomatoes", Value: "91%" }
    ],
    Metascore: "N/A",
    imdbRating: "8.7",
    imdbVotes: "1,340,910",
    imdbID: "tt4574334",
    Type: "series",
    Response: "True"
  },
  {
    Title: "Breaking Bad",
    Year: "2008–2013",
    Rated: "TV-MA",
    Released: "20 Jan 2008",
    Runtime: "49 min",
    Genre: "Crime, Drama, Thriller",
    Director: "Vince Gilligan",
    Writer: "Vince Gilligan",
    Actors: "Bryan Cranston, Aaron Paul, Anna Gunn, Betsy Brandt",
    Plot: "A chemistry teacher diagnosed with inoperable lung cancer turns to manufacturing and selling methamphetamine with a former student in order to secure his family's financial future.",
    Language: "English, Spanish",
    Country: "United States",
    Awards: "Won 16 Primetime Emmys. 162 wins & 248 nominations total",
    Poster: "https://m.media-amazon.com/images/M/MV5BMzU5ZGYzNmQtMTdhYy00OGRiLTg0NmQtYjVjNzliZTg1ZGE4XkEyXkFqcGc@._V1_SX300.jpg",
    Ratings: [
      { Source: "Internet Movie Database", Value: "9.5/10" },
      { Source: "Rotten Tomatoes", Value: "96%" }
    ],
    Metascore: "N/A",
    imdbRating: "9.5",
    imdbVotes: "2,180,450",
    imdbID: "tt0903747",
    Type: "series",
    Response: "True"
  },
  {
    Title: "The Matrix",
    Year: "1999",
    Rated: "R",
    Released: "31 Mar 1999",
    Runtime: "136 min",
    Genre: "Action, Sci-Fi",
    Director: "Lana Wachowski, Lilly Wachowski",
    Writer: "Lilly Wachowski, Lana Wachowski",
    Actors: "Keanu Reeves, Laurence Fishburne, Carrie-Anne Moss, Hugo Weaving",
    Plot: "When a beautiful stranger leads computer hacker Neo to a forbidding underworld, he discovers the shocking truth--the life he knows is the elaborate deception of an evil cyber-intelligence.",
    Language: "English",
    Country: "United States, Australia",
    Awards: "Won 4 Oscars. 42 wins & 52 nominations total",
    Poster: "https://m.media-amazon.com/images/M/MV5BN2NmN2VhMTQtMDNiOS00NDlhLTliMjgtODE2ZTY0ODQyNDRhXkEyXkFqcGc@._V1_SX300.jpg",
    Ratings: [
      { Source: "Internet Movie Database", Value: "8.7/10" },
      { Source: "Rotten Tomatoes", Value: "83%" },
      { Source: "Metacritic", Value: "73/100" }
    ],
    Metascore: "73",
    imdbRating: "8.7",
    imdbVotes: "2,010,000",
    imdbID: "tt0133093",
    Type: "movie",
    BoxOffice: "$172,076,928",
    Production: "Warner Bros., Village Roadshow Pictures",
    Response: "True"
  },
  {
    Title: "Blade Runner 2049",
    Year: "2017",
    Rated: "R",
    Released: "06 Oct 2017",
    Runtime: "164 min",
    Genre: "Action, Drama, Mystery, Sci-Fi",
    Director: "Denis Villeneuve",
    Writer: "Hampton Fancher, Michael Green, Philip K. Dick",
    Actors: "Harrison Ford, Ryan Gosling, Ana de Armas, Dave Bautista",
    Plot: "Young Blade Runner K's discovery of a long-buried secret leads him to track down former Blade Runner Rick Deckard, who's been missing for thirty years.",
    Language: "English, Finnish, Japanese, Hungarian",
    Country: "United States, United Kingdom, Canada, Spain",
    Awards: "Won 2 Oscars. 104 wins & 166 nominations total",
    Poster: "https://m.media-amazon.com/images/M/MV5BNzA1Njg4NzYxOV5BMl5BanBnXkFtZTgwODk5NjU3MzI@._V1_SX300.jpg",
    Ratings: [
      { Source: "Internet Movie Database", Value: "8.0/10" },
      { Source: "Rotten Tomatoes", Value: "88%" },
      { Source: "Metacritic", Value: "81/100" }
    ],
    Metascore: "81",
    imdbRating: "8.0",
    imdbVotes: "640,000",
    imdbID: "tt1856101",
    Type: "movie",
    BoxOffice: "$92,054,159",
    Production: "Alcon Entertainment, Columbia Pictures",
    Response: "True"
  },
  {
    Title: "Spider-Man: Into the Spider-Verse",
    Year: "2018",
    Rated: "PG",
    Released: "14 Dec 2018",
    Runtime: "117 min",
    Genre: "Animation, Action, Adventure, Sci-Fi",
    Director: "Bob Persichetti, Peter Ramsey, Rodney Rothman",
    Writer: "Phil Lord, Rodney Rothman",
    Actors: "Shameik Moore, Jake Johnson, Hailee Steinfeld, Mahershala Ali",
    Plot: "Teen Miles Morales becomes the new Spider-Man and joins other Spider-Heroes from various parallel universes to stop a threat to all reality.",
    Language: "English, Spanish",
    Country: "United States",
    Awards: "Won 1 Oscar. 86 wins & 58 nominations total",
    Poster: "https://m.media-amazon.com/images/M/MV5BMjMwNDkxMTgyNV5BMl5BanBnXkFtZTgwNjkwNTM3NjM@._V1_SX300.jpg",
    Ratings: [
      { Source: "Internet Movie Database", Value: "8.4/10" },
      { Source: "Rotten Tomatoes", Value: "97%" },
      { Source: "Metacritic", Value: "87/100" }
    ],
    Metascore: "87",
    imdbRating: "8.4",
    imdbVotes: "670,000",
    imdbID: "tt4633694",
    Type: "movie",
    BoxOffice: "$190,241,310",
    Production: "Sony Pictures Animation, Marvel Entertainment",
    Response: "True"
  },
  {
    Title: "Severance",
    Year: "2022–",
    Rated: "TV-MA",
    Released: "18 Feb 2022",
    Runtime: "55 min",
    Genre: "Drama, Mystery, Sci-Fi, Thriller",
    Director: "Ben Stiller, Aoife McArdle",
    Writer: "Dan Erickson",
    Actors: "Adam Scott, Zach Cherry, Britt Lower, Patricia Arquette",
    Plot: "Mark leads a team of office workers whose memories have been surgically divided between their work and personal lives. When a mysterious colleague appears outside of work, it begins a journey to discover the truth about their jobs.",
    Language: "English",
    Country: "United States",
    Awards: "Won 2 Primetime Emmys. 25 wins & 89 nominations total",
    Poster: "https://m.media-amazon.com/images/M/MV5BMjA3NTY4NjE0NV5BMl5BanBnXkFtZTgwNTQ1NjY1NDM@._V1_SX300.jpg",
    Ratings: [
      { Source: "Internet Movie Database", Value: "8.7/10" },
      { Source: "Rotten Tomatoes", Value: "97%" },
      { Source: "Metacritic", Value: "83/100" }
    ],
    Metascore: "83",
    imdbRating: "8.7",
    imdbVotes: "225,000",
    imdbID: "tt11280740",
    Type: "series",
    Response: "True"
  },
  {
    Title: "Arcane",
    Year: "2021–2024",
    Rated: "TV-14",
    Released: "06 Nov 2021",
    Runtime: "40 min",
    Genre: "Animation, Action, Adventure, Sci-Fi",
    Director: "Pascal Charrue, Arnaud Delord",
    Writer: "Christian Linke, Alex Yee",
    Actors: "Hailee Steinfeld, Ella Purnell, Kevin Alejandro, Katie Leung",
    Plot: "Set in Utopian Piltover and the oppressed underground of Zaun, the story follows the origins of two iconic League of Legends champions and the power that will tear them apart.",
    Language: "English",
    Country: "United States, France",
    Awards: "Won 4 Primetime Emmys. 22 wins & 10 nominations total",
    Poster: "https://m.media-amazon.com/images/M/MV5BYzA2Nzk5MTAtNGYwNi00MmFiLWE0MjAtYjVlNWUzNGFlNzM1XkEyXkFqcGc@._V1_SX300.jpg",
    Ratings: [
      { Source: "Internet Movie Database", Value: "9.0/10" },
      { Source: "Rotten Tomatoes", Value: "100%" }
    ],
    Metascore: "N/A",
    imdbRating: "9.0",
    imdbVotes: "300,000",
    imdbID: "tt11126994",
    Type: "series",
    Response: "True"
  },
  {
    Title: "Parasite",
    Year: "2019",
    Rated: "R",
    Released: "08 Nov 2019",
    Runtime: "132 min",
    Genre: "Drama, Thriller",
    Director: "Bong Joon Ho",
    Writer: "Bong Joon Ho, Han Jin-won",
    Actors: "Song Kang-ho, Lee Sun-kyun, Cho Yeo-jeong, Choi Woo-shik",
    Plot: "Greed and class discrimination threaten the newly formed symbiotic relationship between the wealthy Park family and the destitute Kim clan.",
    Language: "Korean, English",
    Country: "South Korea",
    Awards: "Won 4 Oscars. 314 wins & 275 nominations total",
    Poster: "https://m.media-amazon.com/images/M/MV5BYWZjMjk3ZTItODQ2ZC00MzA5LWEwYjgtNWU4MmMwISTkGGUxXkEyXkFqcGc@._V1_SX300.jpg",
    Ratings: [
      { Source: "Internet Movie Database", Value: "8.5/10" },
      { Source: "Rotten Tomatoes", Value: "99%" },
      { Source: "Metacritic", Value: "96/100" }
    ],
    Metascore: "96",
    imdbRating: "8.5",
    imdbVotes: "950,000",
    imdbID: "tt6751668",
    Type: "movie",
    BoxOffice: "$53,369,749",
    Production: "Barunson E&A, CJ Entertainment",
    Response: "True"
  },
  {
    Title: "Spirited Away",
    Year: "2001",
    Rated: "PG",
    Released: "28 Mar 2003",
    Runtime: "125 min",
    Genre: "Animation, Adventure, Family, Fantasy",
    Director: "Hayao Miyazaki",
    Writer: "Hayao Miyazaki",
    Actors: "Daveigh Chase, Suzanne Pleshette, Miyu Irino, Rumi Hiiragi",
    Plot: "During her family's move to the suburbs, a sullen 10-year-old girl wanders into a world ruled by gods, witches and spirits, where humans are changed into beasts.",
    Language: "Japanese",
    Country: "Japan",
    Awards: "Won 1 Oscar. 60 wins & 32 nominations total",
    Poster: "https://m.media-amazon.com/images/M/MV5BNTEyNmEwOWUtYzkyOC00ZTQ4LTllZmUtMjk0Y2Y5MmEzYWY1XkEyXkFqcGc@._V1_SX300.jpg",
    Ratings: [
      { Source: "Internet Movie Database", Value: "8.6/10" },
      { Source: "Rotten Tomatoes", Value: "97%" },
      { Source: "Metacritic", Value: "96/100" }
    ],
    Metascore: "96",
    imdbRating: "8.6",
    imdbVotes: "850,000",
    imdbID: "tt0245429",
    Type: "movie",
    BoxOffice: "$15,205,725",
    Production: "Studio Ghibli, Tokuma Shoten",
    Response: "True"
  },
  {
    Title: "Pulp Fiction",
    Year: "1994",
    Rated: "R",
    Released: "14 Oct 1994",
    Runtime: "154 min",
    Genre: "Crime, Drama",
    Director: "Quentin Tarantino",
    Writer: "Quentin Tarantino, Roger Avary",
    Actors: "John Travolta, Uma Thurman, Samuel L. Jackson, Bruce Willis",
    Plot: "The lives of two mob hitmen, a boxer, a gangster and his wife, and a pair of diner bandits intertwine in four tales of violence and redemption.",
    Language: "English, Spanish, French",
    Country: "United States",
    Awards: "Won 1 Oscar. 70 wins & 75 nominations total",
    Poster: "https://m.media-amazon.com/images/M/MV5BYTViYTE3ZGQtNDBlMC00ZTAyLTkyODMtZGRiZDg0MjA2YThkXkEyXkFqcGc@._V1_SX300.jpg",
    Ratings: [
      { Source: "Internet Movie Database", Value: "8.9/10" },
      { Source: "Rotten Tomatoes", Value: "92%" },
      { Source: "Metacritic", Value: "95/100" }
    ],
    Metascore: "95",
    imdbRating: "8.9",
    imdbVotes: "2,210,000",
    imdbID: "tt0110912",
    Type: "movie",
    BoxOffice: "$107,928,762",
    Production: "Miramax, A Band Apart",
    Response: "True"
  }
];
